/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author harry
 */
public class DatosIngresados extends javax.swing.JPanel {

    /**
     * Creates new form DatosIngresados
     */
    public DatosIngresados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtextCedula = new javax.swing.JTextField();
        jtextNombre = new javax.swing.JTextField();
        jtextApellido = new javax.swing.JTextField();
        jtextHoras = new javax.swing.JTextField();
        jbuttonIngresar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtextValorHora = new javax.swing.JTextField();
        jbuttonAtras = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtextTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cedula: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombres: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellidos: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Horas Trabajadas: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jtextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextCedulaActionPerformed(evt);
            }
        });
        add(jtextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 140, -1));
        add(jtextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 140, -1));
        add(jtextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 140, -1));
        add(jtextHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 140, -1));

        jbuttonIngresar.setText("Ingresar");
        add(jbuttonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Capital Inicial:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));
        add(jtextValorHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 140, -1));

        jbuttonAtras.setText("Atras");
        add(jbuttonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 80, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefono:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        add(jtextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-azul.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void jtextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextCedulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JButton jbuttonAtras;
    public javax.swing.JButton jbuttonIngresar;
    public javax.swing.JTextField jtextApellido;
    public javax.swing.JTextField jtextCedula;
    public javax.swing.JTextField jtextHoras;
    public javax.swing.JTextField jtextNombre;
    public javax.swing.JTextField jtextTelefono;
    public javax.swing.JTextField jtextValorHora;
    // End of variables declaration//GEN-END:variables
}
